const mongoose=require("mongoose");
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true
    },
    role:{
        type:String,
        enum:["Admin","Customer"],
        default:"Customer"
    },
    cartItems:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Product"
    }],
    image:{
        type:String,
    }
})
module.exports=mongoose.model("User",userSchema);